---
sudo: required
language: python
python:
    - "2.7"

services:
  - docker

env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING="False"
  matrix:
    # We don't support older versions here. Also upstream doesn't support 4.1
    # when 4.2 is out. https://bugzilla.redhat.com/show_bug.cgi?id=1583222
    - TEST_NAME=4.2

# Install python-pip
addons:
  apt:
    packages:
      - python-pip

install:
  - pip install tox ansible docker-py

  # Check ansible version
  - ansible --version

  # Install ansible role tests requirements
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles/

script:
  # Run sytax checks and linters
  - tox
  # Execute oVirt engine deployment playbook
  - ansible-playbook tests/test-${TEST_NAME}.yml -i tests/inventory --skip-tags skip-travis -vvv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
